### PR TITLE
Add DeepL Free v2, YandexFree, and Yandexv2 translators

### PR DESCRIPTION
**Pull request by bropines**
Poking around on the internet, I found foreign documentation for yandex translate with keys as `trnsl.1.1.1.xxxxxxxxxxxxxxxxxxxxxxxxxx` and rather stupidly added it. Also, "freebies" have been added the translators' versions. In fact, instead of api keys, they use a special service that itself passes requests to where they need to go without a key.

### CODE REVIEW

**Comment by dmMaze** [comment]
Thank you. 
I suggest combine yandex v2 with the existing yandex translator:

Add "api_url" to params like this:
``` python
    params: Dict = {
        'api_key': '',
        'api_url': {
            'type': 'selector',
            'options': [
                'https://translate.api.cloud.yandex.net/translate/v2/translate',
                'https://translate.yandex.net/api/v1.5/tr.json/translate',
            ],
            'select': 'https://translate.api.cloud.yandex.net/translate/v2/translate'
        },
        'delay': 0.0,
    }
```

and in _translate, call the corresponding api according to self.params['api_url']['select']

**Comment by bropines** [comment]
> Thank you. I suggest combine yandex v2 with the existing yandex translator:
> 
> Add "api_url" to params like this:
> 
> ```python
>     params: Dict = {
>         'api_key': '',
>         'api_url': {
>             'type': 'selector',
>             'options': [
>                 'https://translate.api.cloud.yandex.net/translate/v2/translate',
>                 'https://translate.yandex.net/api/v1.5/tr.json/translate',
>             ],
>             'select': 'https://translate.api.cloud.yandex.net/translate/v2/translate'
>         },
>         'delay': 0.0,
>     }
> ```
> 
> and in _translate, call the corresponding api according to self.params['api_url']['select']

How about just making a definition: if the key starts with trnsl then the second api type is used? Banal "if" "else"

**Comment by dmMaze** [comment]
> > Thank you. I suggest combine yandex v2 with the existing yandex translator:
> > Add "api_url" to params like this:
> > ```python
> >     params: Dict = {
> >         'api_key': '',
> >         'api_url': {
> >             'type': 'selector',
> >             'options': [
> >                 'https://translate.api.cloud.yandex.net/translate/v2/translate',
> >                 'https://translate.yandex.net/api/v1.5/tr.json/translate',
> >             ],
> >             'select': 'https://translate.api.cloud.yandex.net/translate/v2/translate'
> >         },
> >         'delay': 0.0,
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and in _translate, call the corresponding api according to self.params['api_url']['select']
> 
> How about just making a definition: if the key starts with `trnsl` then the second api type is used? Banal "if" "else"

Do what seems more appropriate to you.

**Comment by bropines** [comment]
> > > Thank you. I suggest combine yandex v2 with the existing yandex translator:
> > > Add "api_url" to params like this:
> > > ```python
> > >     params: Dict = {
> > >         'api_key': '',
> > >         'api_url': {
> > >             'type': 'selector',
> > >             'options': [
> > >                 'https://translate.api.cloud.yandex.net/translate/v2/translate',
> > >                 'https://translate.yandex.net/api/v1.5/tr.json/translate',
> > >             ],
> > >             'select': 'https://translate.api.cloud.yandex.net/translate/v2/translate'
> > >         },
> > >         'delay': 0.0,
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and in _translate, call the corresponding api according to self.params['api_url']['select']
> > 
> > 
> > How about just making a definition: if the key starts with `trnsl` then the second api type is used? Banal "if" "else"
> 
> Do what seems more appropriate to you.

I'm thinking of leaving the right to choose the API. I added automatic analysis of the entered key. I don’t know why I doubt whether it’s worth adding a manual switching method

**Comment by bropines** [comment]
Then it's up to you, I added. The main thing is to write somewhere that we support both types of tokens

**Comment by bropines** [comment]
Also, I think we need to get rid of DeepL Free. Since the second version of Deepl FreeV2 uses an api proxy server that makes requests itself. 
https://github.com/OwO-Network/DeepLX

**Pull request merged**
