### PR TITLE
Added auto source downloads

### PR DESCRIPTION
**Pull request by ROKOLYT**
Added an option to download manga from sources and then translate them automatically.
Currently supported websites:
+ nhentai.net
+ more to come

For more information on how to use it look into: ballontranslator\ui\pagesources\\_\_init__.py
There you'll find more information on how to get the correct link.

### CODE REVIEW

**Comment by dmMaze** [comment]
Thank you for this pr.  
Can you implement some logic to check&skip existing downloaded images?

**Comment by ROKOLYT** [comment]
> Thank you for this pr.  
> Can you implement some logic to check&skip existing downloaded images?

Sure, I'll do that later today or tomorrow. Also I have a question. How can I add text label before a Text box. Like this:
```[text] [text box]```
I only managed to do it like this:
```[text]
[text box]```

**Comment by dmMaze** [comment]
> How can I add text label before a Text box

Did you mean
image
?
You need to draw the label in the paintEvent of textitem:  
https://github.com/dmMaze/BallonsTranslator/blob/a7831af2111b01c833035486a8fd3e2cf281f394/ballontranslator/ui/textitem.py#L282

**Comment by ROKOLYT** [comment]
No, I meant something like this:
image
and I only managed to do this:
image
Also, I added a check to skip unnecessary downloads and an option to force download.

**Comment by dmMaze** [comment]
> No, I meant something like this:

In short, use QHBoxLayout instead of QVBoxLayout.  
I'll write a qthread wrapper for the download module latter this week.

**Comment by dmMaze** [comment]
> For more information on how to use it look into: ballontranslator\ui\pagesources\__init__.py

Can you provide some nhentai links? All I can find is something like ```https://nhentai.to/g/*``` which failed to pass link check

**Comment by ROKOLYT** [comment]
> > For more information on how to use it look into: ballontranslator\ui\pagesources\__init__.py
> 
> Can you provide some nhentai links? All I can find is something like ```https://nhentai.to/g/*``` which failed to pass link check

You can look into pagesources __init__ for a better explanation. I'll provide some links when I'm on pc.

**Comment by ROKOLYT** [comment]
> > For more information on how to use it look into: ballontranslator\ui\pagesources__init__.py
> 
> Can you provide some nhentai links? All I can find is something like `https://nhentai.to/g/*` which failed to pass link check

I didn't notice you mentioned pagesources. 
In short, it follows a simple scheme. 
https://{server number all numbers work}.nhentai.net/galleries/{gallery number}/{page number}.jpg
Here are some examples:
https://nhentai.net/g/412981/  -> https://i3.nhentai.net/galleries/2285506/1.jpg
https://nhentai.net/g/412963/ -> https://i7.nhentai.net/galleries/2285436/1.jpg
To get those links you need to open the first page of any doujin in a new tab. The link you get links directly to .jpg file
Notice: currently you'll get an error if you paste URLs with pages higher than 9. That happens because the program deletes exactly 5 last characters (1.jpg). This can be easily fixed but I'm not familiar enough with regex to do that.

**Pull request merged**
