### PR TITLE
Add Paddle ocr and EasyOCR

### PR DESCRIPTION
**Pull request by bropines**
- PaddleOCR copes very well with English, Spanish, and Chinese in terms of quality. With Japanese, especially vertical, I’m not at all capable. 
- ~Easy ocr - the most terrible OCR for manga fonts. I added it stupidly so that one person from my circle would be satisfied.~
- Updated lens logging to make it visually clear
- Updated dependencies
- (In theory) Updated the startup bat file on the win system to import cuda libraries. On Mac axis it is necessary to prohibit downloading paddlepaddle-gpu, because I don’t know if it will work there at all.

### CODE REVIEW

**Comment by dmMaze** [comment]
> Easy ocr - the most terrible OCR for manga fonts. I added it stupidly so that one person from my circle would be satisfied.

I find the reason to add it not convincing, just remove it.



> PaddleOCR copes very well with English, Spanish, and Chinese in terms of quality. With Japanese, especially vertical, I’m not at all capable.

Introducing it this way will break some user's current installation. I suggest removing corresponding packages in requirements.txt, and wrapping the source code of ocr_paddle.py in a try-catch to make it optional, like this:
``` python
try:
...
except:
    LOGGER.warning(f'failed to initialize paddle ocr, please install it following https://www.paddlepaddle.org.cn/en/install/quick?docurl')

```

**Comment by bropines** [comment]
Something like this?

```python
try:
    from paddleocr import PaddleOCR
    PADDLE_OCR_AVAILABLE = True
except ImportError:
    PADDLE_OCR_AVAILABLE = False
    logging.warning(
        'PaddleOCR is not installed. Install it by following https://www.paddlepaddle.org.cn/en/install/quick?docurl'
    )
   ```

**Comment by bropines** [comment]
Also, I’m a little stupid, and I don’t understand how to prevent him from sending extra output to the console
```python
[WARNING] utility:get_infer_gpuid:349 - The first GPU is used for inference by default, GPU ID: 0
[2024/10/29 15:03:24] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[WARNING] utility:get_infer_gpuid:349 - The first GPU is used for inference by default, GPU ID: 0
[2024/10/29 15:03:25] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[WARNING] utility:get_infer_gpuid:349 - The first GPU is used for inference by default, GPU ID: 0
[2024/10/29 15:03:32] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
```

**Comment by bropines** [comment]
By the way, I understood why it breaks. It turns out that PIPY contains the release version, and I installed beta 3.0.0.b1. On the good side, it can be placed in the same way as a torch, but I don’t know if that makes sense

**Comment by bropines** [comment]
can be added to launch.py ​​​​as an additional argument like `--install-paddle` which will install this version, similar to torch

```
python -m pip install paddlepaddle-gpu==2.6.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
```

But you can simply enter `pip install paddlepaddle` and it will work on the CPU

**Comment by bropines** [comment]
According to the tests, everything seems to have been checked. Everything works, you can upload to the main branch

**Comment by dmMaze** [comment]
> According to the tests, everything seems to have been checked. Everything works, you can upload to the main branch

I don't see the necessary to add it, make it optional, remove the paddleocr from requirements and wrap the ocr module in a try catch.

**Comment by bropines** [comment]
Well, now I made it not initializable at all if there is no installed library. I don’t know, I’m completely stupid, and I’m asking for help on how to remove my message from the console. I supposedly just wanted to make a module to have a fast and fairly high-quality env engine (I’m not satisfied with the quality of MIT), but here I have to add a bunch of changes. Sorry. I'm just a little tired

**Pull request merged**
