### PR TITLE
Add CT2 Offline Sugoi Translator.

### PR DESCRIPTION
**Pull request by Snowad14**
Sugoi translator is a **Japanese-English** translator created by [mingshiba](https://www.patreon.com/mingshiba), it was trained from visual novels and manga. It can have **as good or better results than deepl** on manga.

It was created with [fairseq](https://github.com/facebookresearch/fairseq) but I converted it with CTranslate2 to have better performance (x2~3 faster).

However I noticed that it still has some problems especially when the sentence has dots in it it can bug and return a sentence with dozens of dots without reasons.

The template is **1 gig** and it is available on this drive link (put "sugoi_translator" in the "data" folder): https://drive.google.com/drive/folders/1KnDlfUM9zbnYFTo6iCbnBaBKabXfnVJm?usp=sharing

### CODE REVIEW

**Comment by dmMaze** [comment]
Thank you for this pr!  

> However I noticed that it still has some problems especially when the sentence has dots in it it can bug and return a sentence with dozens of dots without reasons.

It's the converted model's issue or related to this program?  If it's the latter case, please provide some ja sentences so I can fix it.  

Inpainting thread and translating thread run parallelly by default, it could cause trouble if both of them are computationally intensive, I'll make some necessary modifications before I merge this into master branch.

**Comment by Snowad14** [comment]
This is a problem that comes directly from sugoi translator even without converting the model. The translator is updated quite often so I will update it and I think they will have to fix it soon. I can see to restart the translation if too many dots were detected

**Comment by dmMaze** [comment]
I've just acquired consent from Sugoi's author on discord, I think we're good to integrate it into our program.

**Comment by Snowad14** [comment]
I was just about to commit the fix, instead of recreating a PR just add another .replace("．", "@") then a .replace("@", "．") where there is already one (Actually, sugoi doesn't seem to like this special character and it makes him bug)
image

**Comment by dmMaze** [comment]
> I was just about to commit the fix, instead of recreating a PR just add another .replace("．", "@") where there is already one (Actually, sugoi doesn't seem to like this special character and it makes him bug) image

done ae87e64893aa702c14b1d2195c4e49063b17f7c3

**Comment by dmMaze** [comment]
Does Sugoi support translating English to Japanese?

**Comment by Snowad14** [comment]
no

**Comment by dmMaze** [comment]
Merged into master branch.  

It occasionally produces unreasonable results if run following test multiple times:
image
https://github.com/dmMaze/BallonsTranslator/blob/29e78d52a3a8b359eea6c2affb0427cb58683803/ballontranslator/tests/test_translators.py#L59

**Pull request merged**
