### PR TITLE
Add Windows' and MacOS' OCR, Working But With Small Bugs

### PR DESCRIPTION
**Pull request by tak2hu**
only tested on windows 11 python 3.9 and macos ventura python 3.9

some bugs:
on windows, winocr bug:
- when opening the app and it selects a language from the config, it won't actually apply that config, the user has to manually select the desired language again.
idk how to fix this

on macos, ui bugs and macocr:
- i wanted to implement the fast ocr mode but it has less supported languages than accurate ocr mode, idk how to update the list of languages in macocr
- in view - light mode, some labels are in dark mode
- can't left click (to show context menu or create textbox) on canvas, instead it holds and drags the canvas
- note: installing fugashi python module on macos venture python 3.11 needs to be build from source (no wheels), might add a guide somewhere (also for adding languages in winocr, see below)
- those lines in fw_qt6 I turned them into comments is because the app will crash with a None doesn’t have attribute error (yes for all those 3 lines)

things about for macocr and winocr:
- orientation has not been implemented (idk if it's possible), so vertical japanese sucks (doesn't work)
- installing languages for winocr needs [this guide](https://learn.microsoft.com/en-us/windows/powertoys/text-extractor#troubleshooting), would be nice to have a ui to download modules (including deep learning modules)
- both implementations are really inefficient (i think), i'm a noob soooo yeaaah slow code is what i write

### CODE REVIEW

**Comment by bropines** [comment]
Hmmmm, can you implement paddle or tesseract ocr? Win OCR is great, but you can add more open source engines, and if you need to download models, then I will add a loader, as it is implemented in my loader.

**Comment by tak2hu** [comment]
Tbh I am interested in adding tesseract ocr, paddle ocr, and easy ocr. But to install their languages you would need to go to the terminal but if you (and other users) don’t mind then I’ll add it if dmMaze approves. (I asked and got an ok in Voile Labs discord server, there’s a link in manga-image-translator repo i think)

I want to look into how to add an error pop up if a model is missing and shows “would you like to download it” and a button open a model manager window where you can choose what to download or delete and also has descriptions of each model (detection, ocr, and translation)

but i’m very inexperienced in writing gui, i can only write glue code: copy pasting existing code and integrate it with other projects if there’s references, like those test scripts that are still in the main branch of this repo, those really help. so if i want to add a gui model manager, i’d need a lot more time

Oh and if i do add paddle ocr and easy ocr, idk how to print what languages are supported, so there would be a text field to type the language code to select a language lol.

**Comment by bropines** [comment]
> Tbh I am interested in adding tesseract ocr, paddle ocr, and easy ocr. But to install their languages you would need to go to the terminal but if you (and other users) don’t mind then I’ll add it if dmMaze approves. (I asked and got an ok in Voile Labs discord server, there’s a link in manga-image-translator repo i think)
> 
> I want to look into how to add an error pop up if a model is missing and shows “would you like to download it” and a button open a model manager window where you can choose what to download or delete and also has descriptions of each model (detection, ocr, and translation)
> 
> but i’m very inexperienced in writing gui, i can only write glue code: copy pasting existing code and integrate it with other projects if there’s references, like those test scripts that are still in the main branch of this repo, those really help. so if i want to add a gui model manager, i’d need a lot more time
> 
> Oh and if i do add paddle ocr and easy ocr, idk how to print what languages are supported, so there would be a text field to type the language code to select a language lol.

I can do a graph interface or we can give it to DmMaze. Design on qt is not so complicated

**Comment by Snowad14** [comment]
Just for information, I've tried tesseract and it's really bad, paddle-ocr is better but still inferior to the pre-existing model (but may be good for supporting other languages).

**Comment by tak2hu** [comment]
I tried testing tesseract, paddleocr, and easyocr on vietnamese. paddleocr just returned latin, no diacritics. Tesseract was half accurate but faster than easyocr. Easyocr was the most accurate.

 [here is a video of testing easyocr and tesseract](https://cdn.discordapp.com/attachments/1039002678094725172/1139371852217716766/Screen_Recording_2023-08-11_at_08.34.42.mov)

**Comment by dmMaze** [comment]
https://github.com/sirfz/tesserocr might be more convenient with Windows as it doesn't require additional installation of tesseract (idk whether pytesseract supports it now
and running in line mode (specify some LINE_MODE flag and pass text line instead of a block), make some image processing to make sure the content is black text with white background would significantly boost its performance, yet it still struggles to some irregular font

**Comment by dmMaze** [comment]
> * when opening the app and it selects a language from the config, it won't actually apply that config, the user has to manually select the desired language again.

7764d6c should fix it, need to initialize the engine parameter in setup_ocr (line 336)



> * those lines in fw_qt6 I turned them into comments is because the app will crash with a None doesn’t have attribute error (yes for all those 3 lines)

better to put an if-else check here instead of commenting these out, as I do not have a Mac and have no idea what these do

**Pull request merged**
